DROP TABLE ANIMAL_SHELTER;

CREATE TABLE ANIMAL_SHELTER(
	AREA VARCHAR2(1000) NOT NULL,
	CENTERNAME VARCHAR2(1000) NOT NULL,
	PHONENUMBER VARCHAR2(100) NOT NULL,
	CENTERADDR VARCHAR2(1000) NOT NULL
);

SELECT * FROM ANIMAL_SHELTER;

SELECT COUNT(*) FROM ANIMAL_SHELTER;

SELECT * FROM(
	SELECT	ROWNUM RN, a.* 
	FROM(
		(SELECT * FROM ANIMAL_SHELTER ORDER BY AREA )a
		)
	) WHERE RN >=2 AND RN <=5;