------------------공모 ---------------------------------------------------------
DROP SEQUENCE CON_BOARDNOSQ;
DROP SEQUENCE CON_GROUPNOSQ;
DROP TABLE CONTESTBOARD;

CREATE SEQUENCE CON_BOARDNOSQ;
CREATE SEQUENCE CON_GROUPNOSQ; 

CREATE TABLE CONTESTBOARD(
BOARDNO NUMBER PRIMARY KEY,
GROUPNO NUMBER NOT NULL,
GROUPSQ NUMBER NOT NULL,
REPLYNO NUMBER ,
LIKECNT NUMBER ,
WRITER VARCHAR2(2000) NOT NULL,
TITLE VARCHAR2(3000),
CONTENT CLOB,
REGDATE DATE NOT NULL
);
INSERT INTO CONTESTBOARD VALUES(CON_BOARDNOSQ.NEXTVAL,CON_GROUPNOSQ.NEXTVAL,1,0,0,'작성자','AAA','BBB',SYSDATE);
INSERT INTO CONTESTBOARD VALUES(CON_BOARDNOSQ.NEXTVAL,CON_GROUPNOSQ.NEXTVAL,1,0,0,'작성자1','AAA1','BBB1',SYSDATE);
INSERT INTO CONTESTBOARD VALUES(CON_BOARDNOSQ.NEXTVAL,CON_GROUPNOSQ.NEXTVAL,1,0,0,'작성자2','AAA2','BBB2',SYSDATE);
INSERT INTO CONTESTBOARD VALUES(CON_BOARDNOSQ.NEXTVAL,CON_GROUPNOSQ.NEXTVAL,1,0,0,'작성자3','AAA3','BBB3',SYSDATE);
INSERT INTO CONTESTBOARD VALUES(CON_BOARDNOSQ.NEXTVAL,CON_GROUPNOSQ.NEXTVAL,1,0,0,'작성자4','AAA4','BBB4',SYSDATE);

select * from contestboard;

SELECT COUNT(*) AS CNT FROM CONTESTBOARD WHERE GROUPSQ=1;

		INSERT INTO CONTESTBOARD
		VALUES
		(CON_BOARDNOSQ.NEXTVAL,CON_GROUPNOSQ.NEXTVAL,1,0,0,'asd','dd','ww',SYSDATE);

---------------------------------------------------------------------------------------------
SELECT * FROM CONTESTBOARD;

UPDATE CONTESTBOARD SET LIKECNT = LIKECNT+1 WHERE BOARDNO=5;

SELECT * FROM (SELECT * FROM CONTESTBOARD ORDER BY LIKECNT DESC ) WHERE ROWNUM<=3;

		
		SELECT * FROM ( SELECT ROWNUM RN,a.* FROM CONTESTBOARD a 
		ORDER BY GROUPNO DESC) WHERE RN &gt;=#{begin} AND RN &lt;=#{end}
