DROP TABLE FUNDING;
DROP SEQUENCE FUNSEQ;

CREATE SEQUENCE FUNSEQ;

CREATE TABLE FUNDING(
	FUN_SEQ NUMBER PRIMARY KEY,
	FUNTITLE VARCHAR2(2000) NOT NULL,
	GOALMONEY NUMBER NOT NULL,
	NOWMONEY NUMBER,
	FUNDATE DATE NOT NULL,
	PARTICIPANTS NUMBER,
	FUN_CONTENT VARCHAR2(4000),
	NOTICE VARCHAR2(2),
	CONSTRAINT FUNDING_CHECK_NOTICE CHECK(NOTICE IN('Y','N'))
);

INSERT INTO FUNDING VALUES (FUNSEQ.NEXTVAL, 'TEST FUNDING', 1000, 0, '2019-09-03', 0, '모금 많이 해주세요.', 'Y');

SELECT * FROM FUNDING;

SELECT FUN_SEQ, FUNTITLE, GOALMONEY, NOWMONEY, FUNDATE, PARTICIPANTS, FUN_CONTENT FROM FUNDING ;