DROP TABLE FUNDINGPAY;
CREATE TABLE FUNDINGPAY(
	FUNID VARCHAR2(500),
	FUNTITLE VARCHAR2(2000),
	FUNPAY NUMBER
);
--SELECT sum(funpay) FROM fundingpay;
--INSERT INTO fundingpay values('admin','test funding',600);

SELECT * FROM FUNDINGPAY;

INSERT INTO FUNDINGPAY VALUES ('admin', 'TEST FUNDING', 100);

SELECT SUM(FUNPAY) AS SUM_FUNPAY FROM FUNDINGPAY 
WHERE (SELECT FUNTITLE FROM FUNDINGPAY
		GROUP BY FUNTITLE);
		
SELECT FUNTITLE, SUM(FUNPAY) AS FUNPAY FROM FUNDINGPAY WHERE FUNTITLE LIKE 'TEST FUNDING' GROUP BY FUNTITLE;

SELECT FUNTITLE, SUM(FUNPAY) AS FUNPAY FROM FUNDINGPAY GROUP BY 'TEST FUNDING';

SELECT COUNT(DISTINCT FUNID) AS FUNPAY FROM FUNDINGPAY WHERE FUNTITLE LIKE 'TEST FUNDING' GROUP BY FUNTITLE;



