/**********************************/
/* Table Name: 회원 */
/**********************************/
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MEMBER;
DROP SEQUENCE USERSEQ;
CREATE SEQUENCE USERSEQ;
CREATE TABLE MEMBER( 
USERNUM NUMBER PRIMARY KEY, 
NAME VARCHAR2(100) NOT NULL,
ID VARCHAR2(100) UNIQUE,
PW VARCHAR2(100) NOT NULL,
PHONE VARCHAR2(100) NOT NULL,
EMAIL VARCHAR2(100) UNIQUE NOT NULL,
ADDR VARCHAR2(100) NOT NULL,
ZONECODE VARCHAR2(100) NOT NULL,
ENABLEDDB VARCHAR2(100) NOT NULL,
ROLE VARCHAR2(100) NOT NULL,
JOINDATE DATE NOT NULL,
PERPAY VARCHAR2(10),
CONSTRAINT CON_PERPAY CHECK (PERPAY IN ('Y','N')),
CONSTRAINT CON_ENABLED CHECK (ENABLEDDB IN ('Y','N')),
CONSTRAINT CON_ROLE CHECK (ROLE IN ('ROLE_ADMIN','ROLE_USER'))
);

DELETE FROM MEMBER WHERE USERNUM = 1;

INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'관리자','admin','admin123','010-7723-7077','brooke1994@naver.com','서초구 역삼동','120-10',1,'ADMIN',SYSDATE);
INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'user1','user1','123','010-7777-7077',
'alice1994@naver.com','강남구 개포동','25-18',1,'USER',SYSDATE);
SELECT * FROM MEMBER WHERE 7 <=(SELECT TO_DATE(TO_CHAR(SYSDATE, 'YYYYMMDD')) -JOINDATE FROM MEMBER);
SELECT * FROM MEMBER;

UPDATE MEMBER SET ROLE='ROLE_ADMIN' WHERE ID='woo'

SELECT TO_DATE(TO_CHAR(SYSDATE, 'YYYYMMDD')) - JOINDATE FROM MEMBER;
INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'관리자','admin','admin123','010-7723-7077',
'brooke1994@naver.com','서초구 역삼동','120-10','Y','ROLE_ADMIN','2019-08-20','N');
ENABLED VARCHAR2(100) NOT NULL,
ROLE VARCHAR2(100) NOT NULL,
CONSTRAINT CON_ROLE CHECK (ROLE IN ('ADMIN','USER')),
CONSTRAINT CON_ENABLED CHECK (ENABLED IN ('Y','N'))
);

INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'관리자','admin','admin123','010-7723-7077',
'brooke1994@naver.com','서초구 역삼동','120-10','Y','ADMIN');
INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'user1','user1','123','010-7777-7077',
'alice1994@naver.com','강남구 개포동','25-18',1,'USER','2019-08-20');
INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'user3','user3','123','010-7777-7077',
'alice1994@naver.com','강남구 개포동','25-18',1,'USER');
INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'user3','user2','123','010-7777-7077',
'alice1994@naver.com','강남구 개포동','25-18','N','ROLE_USER','2019-08-20','N');
'alice1994@naver.com','강남구 개포동','25-18',1,'USER');
INSERT INTO MEMBER VALUES(USERSEQ.NEXTVAL,'user4','user4','1234','010-4477-7077',
'jeni_jung','문정동','1218','N','USER');


SELECT USERNUM, ID AS username,PW AS password, NAME,PHONE,EMAIL,ADDR,ZONECODE,ENABLED,ROLE FROM MEMBER WHERE ID = 'woo1'

SELECT * FROM MEMBER WHERE ID='admin';
SELECT * FROM AUTHORITIES

SELECT ID FROM MEMBER WHERE NAME='aa' AND EMAIL='clickbw1004@naver.com' 

COMMENT ON TABLE MEMBER is '회원';
COMMENT ON COLUMN MEMBER.ID is '아이디';
COMMENT ON COLUMN MEMBER.PW is '비밀번호';
COMMENT ON COLUMN MEMBER.ENABLED is '계정사용여부';


ALTER TABLE users ADD CONSTRAINT IDX_users_PK PRIMARY KEY (username);

-- 회원 데이터 입력
INSERT INTO users (username, password, enabled) VALUES ('user', '1', 1);
INSERT INTO users (username, password, enabled) VALUES ('admin', '1', 1);

-- 회원 권한 입력
INSERT INTO AUTHORITIES (ID, AUTHORITY) VALUES ('user2', 'ROLE_USER');
INSERT INTO AUTHORITIES (ID, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (ID, AUTHORITY) VALUES ('user3', 'ROLE_USER');

